USE [master]
GO

/****** Object:  Database [ForumDatabase]    Script Date: 02.02.2024 13:48:16 ******/
CREATE DATABASE [ForumDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ForumDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ForumDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ForumDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ForumDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ForumDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ForumDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ForumDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ForumDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ForumDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ForumDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [ForumDatabase] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ForumDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ForumDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ForumDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ForumDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ForumDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ForumDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ForumDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ForumDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ForumDatabase] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ForumDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ForumDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ForumDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ForumDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ForumDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ForumDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ForumDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ForumDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ForumDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [ForumDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ForumDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ForumDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ForumDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ForumDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ForumDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ForumDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ForumDatabase] SET  READ_WRITE 
GO

